/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stopwatch;

/**
 *
 * @author PrithviDevKumar
 */
public class Stopwatch extends javax.swing.JFrame {

    static int hours = 0;
    static int seconds = 0;
    static int minutes = 0;
    static int milliseconds = 0;
    
    static boolean state = true;
    public Stopwatch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        h = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        ms = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1050, 2));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        h.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        h.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h.setText("00:");
        h.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 27, 46, 41));

        m.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        m.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m.setText("00:");
        m.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 27, 46, 41));

        s.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s.setText("00:");
        s.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 27, 46, 41));

        ms.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ms.setText("00");
        ms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 29, 36, 41));

        start.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jLayeredPane1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 81, -1, -1));

        stop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        jLayeredPane1.add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 117, 63, -1));

        reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jLayeredPane1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 153, -1, -1));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 198));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stopwatch/exit.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 0, 25, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stopwatch/minimize.png"))); // NOI18N
        minimize.setContentAreaFilled(false);
        minimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 0, 25, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stopwatch/clock.png"))); // NOI18N
        jLabel1.setText("Stopwatch");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stopwatch/lg.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setExtendedState(Stopwatch.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        state = true;
        Thread t = new Thread()
        {
            public void run(){
                for(;;){
                    if(state == true){
                        try{
                            sleep(1);
                            
                            if(milliseconds > 1000){
                                milliseconds = 0;
                                seconds++;
                            }
                            
                            else if(seconds > 60){
                                seconds = 0;
                                milliseconds = 0;
                                minutes++;
                            }
                            
                            else if(minutes > 60){
                                seconds = 0;
                                milliseconds = 0;
                                minutes = 0;
                                hours++;
                            }
                            
                            ms.setText(":"+milliseconds);
                            milliseconds++;
                            s.setText(":"+seconds);
                            m.setText(":"+minutes);
                            h.setText(""+hours);
                            
                        }
                        catch(Exception e){
                            
                        }
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        state = false;
    }//GEN-LAST:event_stopActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        state = false;
        hours = 0 ;
        minutes = 0;
        seconds = 0;
        milliseconds = 0;
        
        
        h.setText("00:");
        m.setText(":00");
        s.setText(":00");
        ms.setText("00");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stopwatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel h;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel m;
    private javax.swing.JButton minimize;
    private javax.swing.JLabel ms;
    private javax.swing.JButton reset;
    private javax.swing.JLabel s;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
